project:
  type: book

book:
  title: "40.622.81 – Statistical Methods in Public Health II"
  author: "Elham Ali"
  date: "11/13/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - lecture1.qmd
    - lecture2.qmd
    - lecture3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
editor: visual